### ISSUE TITLE
Call to a member function getConfig() on null

### ISSUE THREAD

**Issue by magentix** [Cecilapp/Cecil#1456]
### Describe the bug

Hello,

When I try to add a new page, I get the following error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getConfig() on null in phar:///var/www/cecil.test/cecil.phar/src/Command/NewPage.php:70
Stack trace:
#0 phar:///var/www/cecil.test/cecil.phar/vendor/symfony/console/Command/Command.php(298): Cecil\Command\NewPage->execute()
```

### To reproduce

1. Create a new website

```
php cecil.phar new:site
Creating a new website...
- title: Test
- baseline (~ 20 characters): Hello!
- baseurl (e.g.: https://cecil.app/): https://www.example.com
- description (~ 250 characters): 
Done!
```

2. Create a new page:

```
php cecil.phar new:page test.md
```

### Expected behavior

A new page generated.

### Version

6.2.5

### Operating System

Ubuntu

### Relevant log output

```shell
PHP Fatal error:  Uncaught Error: Call to a member function getConfig() on null in phar:///var/www/cecil/cecil.phar/src/Command/NewPage.php:70
Stack trace:
#0 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Command/Command.php(298): Cecil\Command\NewPage->execute()
#1 phar:///var/www/cecil/cecil.phar/src/Command/AbstractCommand.php(116): Symfony\Component\Console\Command\Command->run()
#2 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(1028): Cecil\Command\AbstractCommand->run()
#3 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 phar:///var/www/cecil/cecil.phar/bin/cecil(82): Symfony\Component\Console\Application->run()
#6 /var/www/cecil/cecil.phar(14): require('...')
#7 {main}
  thrown in phar:///var/www/cecil/cecil.phar/src/Command/NewPage.php on line 70

Fatal error: Uncaught Error: Call to a member function getConfig() on null in phar:///var/www/cecil/cecil.phar/src/Command/NewPage.php:70
Stack trace:
#0 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Command/Command.php(298): Cecil\Command\NewPage->execute()
#1 phar:///var/www/cecil/cecil.phar/src/Command/AbstractCommand.php(116): Symfony\Component\Console\Command\Command->run()
#2 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(1028): Cecil\Command\AbstractCommand->run()
#3 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///var/www/cecil/cecil.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 phar:///var/www/cecil/cecil.phar/bin/cecil(82): Symfony\Component\Console\Application->run()
#6 /var/www/cecil/cecil.phar(14): require('...')
#7 {main}
  thrown in phar:///var/www/cecil/cecil.phar/src/Command/NewPage.php on line 70
```

**Comment by ArnaudLigny** [comment]
Hello @magentix, thanks a lot for your report: it was a classic "quick change without full integration tests" :-/

I'm working on a fix.

**Comment by ArnaudLigny** [comment]
@magentix could you try again with the release 6.2.6 (`php cecil.phar self-update`)?

**Comment by magentix** [comment]
@ArnaudLigny Yes it works now! Thanks :)
