### ISSUE TITLE
Doesn't work with PHP 7.4

### ISSUE THREAD

**Issue by tbalsys** [Cecilapp/Cecil#789]
**Describe the bug**
cecil 5.27.0 does not build the site when using PHP version 7.4. It spits this error:

```
Fatal error: Uncaught Error: Object of class Cecil\Collection\Page\Page could not be converted to string in phar:///cecil.phar/src/Assets/Url.php:78
Stack trace:
#0 phar:///cecil.phar/src/Renderer/Twig/Extension.php(308): Cecil\Assets\Url->__construct(Object(Cecil\Builder), Object(Cecil\Collection\Page\Page), Array)
#1 phar:///cecil.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(174): Cecil\Renderer\Twig\Extension->url(Object(Cecil\Collection\Page\Page), Array)
#2 phar:///cecil.phar/vendor/twig/twig/src/Template.php(184): __TwigTemplate_2b3657fd54e1c2053ca6bff8ea8a797a7609ba5520f54283c502a6835b84d4c2->block_head(Array, Array)
#3 phar:///cecil.phar/vendor/twig/twig/src/Environment.php(418) : eval()'d code(54): Twig\Template->displayBlock('head', Array, Array)
#4 phar:///cecil.phar/vendor/twig/twig/src/Template.php(407): __TwigTemplate_2b3657fd54e1c2053ca6bff8ea8a797a7609ba5520f54283c502a6835b84d4c2->doDisplay(Array, Array)
#5 phar:///cecil.phar/vendor/twig/twig/src/Template.php(380): Twig\Template->displayW in phar:///cecil.phar/src/Assets/Url.php on line 78
```

**To Reproduce**
Install PHP 7.4
Download and install cecil.phar ver 5.27.0
Execute this:
```
./cecil.phar new:site
./cecil.phar build
```

One liner:
```
docker run -it --rm php:7.4-cli bash -c "curl -LO https://cecil.app/cecil.phar && chmod +x cecil.phar && ./cecil.phar new:site && ./cecil.phar build"
```

**Expected behavior**
cecil should build the site without error on PHP 7.4. 

So as it works on PHP 7.3:
```
docker run -it --rm php:7.3-cli bash -c "curl -LO https://cecil.app/cecil.phar && chmod +x cecil.phar && ./cecil.phar new:site && ./cecil.phar build"
```

**Additional context**
Testing on OS: Linux 5.6.11-1-MANJARO

**Comment by Narno** [comment]
Hello @tbalsys, thx a lot for your report. Could you (re)try with version 5.27.2?

**Comment by tbalsys** [comment]
I can't find `cecil.phar` in 5.27.2 release assets.

**Comment by tbalsys** [comment]
That was a quick fix. Now it works. Tested on with PHP 7.4.5 inside docker and without docker.

**Comment by Narno** [comment]
Thx!

There was 2 problems:
1. a silent error "object to string conversion" with PHP <7.4
2. a dependence to a lib that works with PHP 7.1 but not with 7.4: and I want to keep 7.1 compatible for the moment :-)
